doctrine_mongodb:
  connections:
    default:
      server: 'mongodb://mongo:27017'
      options:
          username: '%env(resolve:MONGODB_USER)%'
          password: '%env(resolve:MONGODB_PASSWORD)%'
  default_database: '%env(MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          dir: "%kernel.project_dir%/src/Infrastructure/Symfony/Document/"
          mapping: true
          type: attribute
          prefix: 'Infrastructure\Symfony\Document'
          is_bundle: false
          alias: App
